blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC General Discussion"
    url: "https://github.com/langgenius/syncless-issue/issues"
    about: Search existing issues before opening a new one.
  - name: "\U0001F310 Syncless Website"
    url: "https://syncless.ai"
    about: Visit the official Syncless website.
  - name: "\U0001F4E8 Discord Community"
    url: "https://discord.com/invite/PBRjrhHsr"
    about: Join our Discord community for discussions and support.
